#!/usr/bin/env ksh

# resolution
xrandr --auto --output Virtual-1  --mode 1440x900

# read variables
export ENV="$HOME/.kshrc"
[[ -f $HOME/.profile ]] && . $HOME/.profile
[[ -f $HOME/.kshrc ]] && . $HOME/.kshrc

#setxkbmap -option ctrl:swapcaps
[[ -f $XDG_CONFIG_HOME/x11/Xmodmap ]] && xmodmap $XDG_CONFIG_HOME/x11/Xmodmap

# xresources
[[ -f $XDG_CONFIG_HOME/x11/Xresources ]] && xrdb -merge $XDG_CONFIG_HOME/x11/Xresources

# audio
start-pulseaudio-x11 &

# for java apps
wmname LG3D

